<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Municipio;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipios = [
            "Acuitzio",  
            "Aguililla",  
            "Álvaro Obregón",  
            "Angamacutiro",  
            "Angangueo",  
            "Apatzingán",  
            "Aporo",  
            "Aquila",  
            "Ario",  
            "Arteaga",  
            "Briseñas",  
            "Buenavista",  
            "Carácuaro",  
            "Coahuayana",  
            "Coalcomán de Vázquez Pallares",  
            "Coeneo",  
            "Contepec",  
            "Copándaro",  
            "Cotija",  
            "Cuitzeo",  
            "Charapan",  
            "Charo",  
            "Chavinda",  
            "Cherán",  
            "Chilchota",  
            "Chinicuila",  
            "Chucándiro",  
            "Churintzio",  
            "Churumuco",  
            "Ecuandureo",  
            "Epitacio Huerta",  
            "Erongarícuaro",  
            "Gabriel Zamora",  
            "Hidalgo",  
            "La Huacana",  
            "Huandacareo",  
            "Huaniqueo",  
            "Huetamo",  
            "Huiramba",  
            "Indaparapeo",  
            "Irimbo",  
            "Ixtlán",  
            "Jacona",  
            "Jiménez",  
            "Jiquilpan",  
            "Juárez",  
            "Jungapeo",  
            "Lagunillas",  
            "Madero",  
            "Maravatío",  
            "Marcos Castellanos",  
            "Lázaro Cárdenas",  
            "Morelia",  
            "Morelos",  
            "Múgica",  
            "Nahuatzen",  
            "Nocupétaro",  
            "Nuevo Parangaricutiro",  
            "Nuevo Urecho",  
            "Numarán",  
            "Ocampo",  
            "Pajacuarán",  
            "Panindícuaro",  
            "Parácuaro",  
            "Paracho",  
            "Pátzcuaro",  
            "Penjamillo",  
            "Peribán",  
            "La Piedad",  
            "Purépero",  
            "Puruándiro",  
            "Queréndaro",  
            "Quiroga",  
            "Cojumatlán de Régules",  
            "Los Reyes",  
            "Sahuayo",  
            "San Lucas",  
            "Santa Ana Maya",  
            "Salvador Escalante",  
            "Sengio",  
            "Susupuato",  
            "Tacámbaro",  
            "Tancítaro",  
            "Tangamandapio",  
            "Tangancícuaro",  
            "Tanhuato",  
            "Taretan",  
            "Tarímbaro",  
            "Tepalcatepec",  
            "Tingambato",  
            "Tingüindín",  
            "Tiquicheo de Nicolás Romero",  
            "Tlalpujahua",  
            "Tlazazalca",  
            "Tocumbo",  
            "Tumbiscatío",  
            "Turicato",  
            "Tuxpan",  
            "Tuzantla",  
            "Zintzuntzan",  
            "Tzitzio",  
            "Uruapan",  
            "Venustiano Carranza",  
            "Villamar",  
            "Vista Hermosa",  
            "Yurécuaro",  
            "Zacapu",  
            "Zamora",  
            "Zináparo",  
            "Zinapécuaro",  
            "Ziracuaretiro",  
            "Zitácuaro",  
            "José Sixto Verduzco"
        ];

        foreach ($municipios as $municipio) {
            Municipio::create([
                'descripcion' => $municipio
            ]);
        }
    }
}
